version: '3.8'

services:
  auth:
    build:
      context: ./auth
    ports:
      - "17007:17007"

  score:
    build:
      context: ./score
    ports:
      - "18008:18008"

  composition1:
    build:
      context: ./composition
    environment:
      - SCORE_THRESHOLD=0.5

  composition2:
    build:
      context: ./composition
    environment:
      - SCORE_THRESHOLD=0.5

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - composition1
      - composition2