# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\"\x1d\n\x0cScoreRequest\x12\r\n\x05login\x18\x01 \x01(\t\"\x1e\n\rScoreResponse\x12\r\n\x05score\x18\x01 \x01(\x01\".\n\x0b\x41uthRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1f\n\x0c\x41uthResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x32\x32\n\x05Score\x12)\n\x08GetScore\x12\r.ScoreRequest\x1a\x0e.ScoreResponse2:\n\x04\x41uth\x12\x32\n\x13ValidateCredentials\x12\x0c.AuthRequest\x1a\r.AuthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCOREREQUEST']._serialized_start=18
  _globals['_SCOREREQUEST']._serialized_end=47
  _globals['_SCORERESPONSE']._serialized_start=49
  _globals['_SCORERESPONSE']._serialized_end=79
  _globals['_AUTHREQUEST']._serialized_start=81
  _globals['_AUTHREQUEST']._serialized_end=127
  _globals['_AUTHRESPONSE']._serialized_start=129
  _globals['_AUTHRESPONSE']._serialized_end=160
  _globals['_SCORE']._serialized_start=162
  _globals['_SCORE']._serialized_end=212
  _globals['_AUTH']._serialized_start=214
  _globals['_AUTH']._serialized_end=272
# @@protoc_insertion_point(module_scope)
